
[functions.enviar-confirmacao-pedido]
enabled = true
verify_jwt = true
import_map = "./functions/enviar-confirmacao-pedido/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/enviar-confirmacao-pedido/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/enviar-confirmacao-pedido/*.html" ]

[functions.exportar-pedido-csv]
enabled = true
verify_jwt = true
import_map = "./functions/exportar-pedido-csv/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/exportar-pedido-csv/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/exportar-pedido-csv/*.html" ]
